# Generated by Django 4.2.7 on 2025-06-05 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterMeter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('meter_type', models.CharField(choices=[('analog', 'Analog Meter'), ('digital', 'Digital Meter'), ('ultrasonic', 'Ultrasonic Meter')], default='digital', max_length=20)),
                ('installation_date', models.DateField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_meters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WaterUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('volume', models.DecimalField(decimal_places=3, help_text='Volume in liters', max_digits=10)),
                ('flow_rate', models.DecimalField(decimal_places=3, help_text='Flow rate in L/min', max_digits=8)),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, help_text='Water temperature in °C', max_digits=5, null=True)),
                ('is_leak', models.BooleanField(default=False)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='meter.watermeter')),
            ],
            options={
                'verbose_name_plural': 'Water Usages',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('leak', 'Water Leak Detected'), ('high_usage', 'Unusually High Water Usage'), ('inactive', 'Meter Inactive'), ('other', 'Other')], max_length=20)),
                ('message', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='meter.watermeter')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
